### ISSUE TITLE
打开文件错误

### ISSUE THREAD

**Issue by sugarandgugu** [YiBin16/KaoYan-English_1#1]
<img width="790" alt="image" src="https://github.com/user-attachments/assets/be410260-1b3d-47e7-b3e9-b04ab860dd73">
？？？

**Comment by JimmyKudo16** [comment]
我打看是没问题的,要不你留一下邮箱,我发你邮箱

**Comment by sugarandgugu** [comment]
好的麻烦了，谢谢。sugaarvapeur@gmail.com

**Comment by JimmyKudo16** [comment]
不客气的    邮件已发送    注意查收
